#!/usr/bin/env bash

set -e -u -x

REPOS="$HOME/.homesick/repos"

if [ ! -d "$REPOS/homeshick" ]; then
  git clone https://github.com/andsens/homeshick.git "$REPOS/homeshick"
fi

mkdir -p $HOME/.vim/swapfiles

source "$REPOS/homeshick/homeshick.sh"
homeshick link dotfiles
