#!/usr/bin/env bash

set -e -u -x

REPOS="$HOME/.homesick/repos"

if [ ! -d "$REPOS/homeshick" ]; then
  git clone https://github.com/andsens/homeshick.git "$REPOS/homeshick"
fi

source "$REPOS/homeshick/homeshick.sh"
homeshick link dotfiles

(cd "$HOME/.homebrew" && (brew update --verbose || brew update --verbose) && brew bundle --verbose)

vim +PlugInstall +qall
