tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "chef/homebrew-chef"

brew "Arkweid/lefthook/lefthook"
brew "asdf"
brew "git"
brew "httpie"
brew "libpq"
brew "neovim"
brew "pwgen"
brew "ripgrep"
brew "rsync"
brew "zsh"

brew "aws-iam-authenticator"
brew "awscli"
brew "gnu-getopt"
brew "helm"
brew "helmfile"
brew "terraform"

cask "alfred"
cask "bartender"
cask "chef-workstation"
cask "dbeaver-community"
cask "docker"
cask "firefox"
cask "fujitsu-scansnap-home"
cask "google-chrome"
cask "gpg-suite"
cask "imageoptim"
cask "insomnia"
cask "little-snitch"
cask "micro-snitch"
cask "oracle-jdk"
cask "vimr"
cask "virtualbox"
cask "virtualbox-extension-pack"

mas "1Password 7", id: 1333542190
mas "Slack", id: 803453959
mas "The Unarchiver", id: 425424353
mas "Time Out - Break Reminders", id: 402592703
mas "Wipr", id: 1320666476
mas "Xcode", id: 497799835
